language: java
jdk:
  - oraclejdk8
secure: "xQhkZpBI91jFzIz4aB9hcwItyoEmjg3onBCQ2rnnGitBjQm8BNLphgR/oYG+3Pq9g04yCbWRoYQTBECd7d6GkYGdYl8qZX15RDdGrefeRSa8ipqC0B16unsKP7WZ1SrwKBBF2H0g1ieiHErjoxs8iWvZcXzo0Vavd9WG4YVZqwup1xnCYMRPTjR/gMYpFxRKWagVyaTlFDu4cKehdbfTrFrILk425wnFJypu9lsh43buMpF2OmnChnkYU8IleJ+3dw4bEfD0IHI1Th3dPH8gLIQxhacuuEtew4VglFdnOViUFbwY+qkDMMNoaD/UhpOUPc2928hTvDRorWPfwEfcN9Tum/NDx81JGDzz8/nLb4dG+9HWwlKQXBDsSFKe+I2X5kq8Xuyei011U3qeWDsUU06uFfikYf1GrpBIn0g4VL/jf3Zw2G4len84PEbWQrsDAeRGWNTmmXhk8myxKFfAG10M+5WOwqShs3ssExnpdFyc+LDbIWKlNDY9vmHEv2v1f4ro3v/+qsE7WLbSyL+cbWFQHNCs4B1KjUd15QKbuQ8ACaeqVZ13qqI0ojzDV7kWXnJzj1V5iCH86z+EeKX6s9nNJMu4767myAXmJAiLJ158WwsQX7m3bGceU5UxZ1ycNhWlUaRQ1T62FJrCVYons0iDFbwUcnKjsve5q38r+kg="
before_install:
  - chmod +x .travis-ci/push-site-to-gh-pages.sh
install: mvn install site -DskipTests=true
after_success: .travis-ci/push-site-to-gh-pages.sh
