# Site settings
title: Spring Framework - Chronicle Collection Support
email: dave@osframework.org
description: > # this means to ignore newlines until "baseurl:"
  Spring framework module for integration of Chronicle high-performance collections.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: osframework
github_username:  osframework

# Build settings
markdown: kramdown
